---
{{- with .Values.influxdb }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Values.namespace }}
  name: "{{ .name }}-configmap"
data:
{{ ($.Files.Glob "config/influxdb/influxdb.conf").AsConfig | indent 2 }}

{{- end }}
