---
{{- with .Values.prometheus }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Values.namespace }}
  name: "{{ .name }}-configmap"
data:
{{ ($.Files.Glob "config/prometheus/alert.rules").AsConfig | indent 2 }}
{{ ($.Files.Glob "config/prometheus/prometheus.yml").AsConfig | indent 2 }}

{{- end }}
