---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $.Values.namespace }}
  name: credentials
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: {{ $.Values.secrets.GF_SECURITY_ADMIN_PASSWORD }}
  INFLUX_DB_FLUX_TOKEN: {{ $.Values.secrets.INFLUX_DB_FLUX_TOKEN }}
  INFLUX_TOKEN: {{ $.Values.secrets.INFLUX_TOKEN }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $.Values.namespace }}
  name: seeds
type: Opaque
stringData:
{{- range $.Values.inputs }}
{{ .short_name | upper | indent 2 }}_SEED: {{ .network_monitor_seed | quote }}
{{- end }}
