{
 "title": "Network Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "SHOW TAG VALUES FROM \"node\" WITH KEY = \"network\" "
    }
   }
  ]
 },
 "panels": [
  {
   "type": "gauge",
   "description": "Warnings and Errors Status",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "Warning = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) => \r\n     r._measurement == \"node\" and \r\n     r._field == \"status_warnings\" and \r\n     r.network == \"${network}\"\r\n     )\r\n\r\nError = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"status_errors\" and \r\n    r.network == \"${network}\" \r\n  )\r\n\r\n  join(\r\n    tables: {status_warnings:Warning, status_errors:Error},\r\n    on: [\"_time\", \"_stop\", \"_start\", \"host\", \"name\", \"url\", \"network\", \"_measurement\"],\r\n)\r\n\r\n  |> map(fn: (r) => ({r with\r\n    Final: if r._value_status_errors >= 1 then\r\n      0\r\n    else if r._value_status_warnings >= 1 then\r\n      1\r\n    else 3\r\n    })\r\n    )"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Network Average Node Connectivity",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Reachable Nodes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Pool_info_Total_nodes_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Total Nodes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Pool_info_Total_nodes_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Write Failure Threshhold",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT max(\"response_result_data_Pool_info_Total_nodes_count\") - max(\"response_result_data_Pool_info_f_value\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Pool_info_Total_nodes_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Status Errors",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "node",
     "query": " from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"node_status_errors\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()",
     "select": [
      [
       { "params": [ "status_errors" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Status Warnings",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Warnings",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       { "params": [ "status_warnings" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  { "title": "Txn Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Read Txns per Second",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Txns per Second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_average-per-second_read-transactions\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_average-per-second_read-transactions"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Txns per Second",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Txns per Second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_average-per-second_write-transactions"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  { "title": "Request Timeouts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Ordering Phase Req Timeouts",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "alias": "Request timeouts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Requests_timeouts_Ordering_phase_req_timeouts"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Propagates Phase Req Timeouts",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "alias": "Request timeouts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Requests_timeouts_Propagates_phase_req_timeouts"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  { "title": "Transaction Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Uncommitted Ledger Txns",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Ledger 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Uncommitted_ledger_txns_0_Count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Ledger 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Uncommitted_ledger_txns_1_Count\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Uncommitted_ledger_txns_1_Count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Ledger 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Uncommitted_ledger_txns_1_Count\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Uncommitted_ledger_txns_2_Count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Ledger 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Uncommitted_ledger_txns_1_Count\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Uncommitted_ledger_txns_3_Count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Ledger Txn Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Txn Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_transaction-count_ledger"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Audit Txn Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Txn Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_transaction-count_audit"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Config Txn Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Txn Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_transaction-count_config"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool Txn Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Txn Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_transaction-count_pool"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "1001 Txn Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Txn Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_transaction-count_1001\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_transaction-count_pool"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Catchup Txn Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Ledger 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Ledger 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_1\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Ledger 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_2\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Ledger 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_3\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Ledger 1001",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_1001\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Master Throughput",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Throughput",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_master throughput\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_master throughput"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Master Throughput Ratio",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "alias": "Master throughput ratio",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_master throughput ratio"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "alias": "Throughput 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_throughput_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Throughput 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_throughput_1\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_throughput_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Throughput 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_throughput_2\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_throughput_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Throughput 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_throughput_3\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_throughput_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Throughput 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_throughput_4\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_throughput_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Throughput 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_throughput_5\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_throughput_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Throughput 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_throughput_6\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_throughput_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Backup Throughput",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "alias": "Avg backup throughup",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_avg backup throughput"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Master Req. Latencies",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "alias": "Request Latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_max master request latencies\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_max master request latencies"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Client Avg Request Latencies",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Avg Req. Latencies 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_client avg request latencies_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Avg Req. Latencies 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_client avg request latencies_1\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_client avg request latencies_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Avg Req. Latencies 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_client avg request latencies_2\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_client avg request latencies_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Avg Req. Latencies 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_client avg request latencies_3\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_client avg request latencies_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Avg Req. Latencies 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_client avg request latencies_4\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_client avg request latencies_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Avg Req. Latencies 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_client avg request latencies_5\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_client avg request latencies_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Avg Req. Latencies 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_client avg request latencies_6\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_client avg request latencies_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Ordered Request Durations",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "alias": "Request 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_ordered request durations_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Request 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_ordered request durations_1\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_ordered request durations_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Request 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_ordered request durations_2\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_ordered request durations_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Request 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_ordered request durations_3\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_ordered request durations_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Request 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_ordered request durations_4\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_ordered request durations_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Request 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_ordered request durations_5\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_ordered request durations_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Request 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_ordered request durations_6\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_ordered request durations_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Request Counts",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "alias": "Total Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_total requests"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Count 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_ordered request counts_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Count 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_ordered request counts_1\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_ordered request counts_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Count 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_ordered request counts_2\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_ordered request counts_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Count 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_ordered request counts_3\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_ordered request counts_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Count 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_ordered request counts_4\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_ordered request counts_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Count 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_ordered request counts_5\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_ordered request counts_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Count 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_ordered request counts_6\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_ordered request counts_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Instances Started",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "alias": "Instance 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_instances started_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Instance 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_instances started_1\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_instances started_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Instance 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_instances started_2\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_instances started_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Instance 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_instances started_3\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_instances started_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Instance 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_instances started_4\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_instances started_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Instance 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_instances started_5\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_instances started_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    },
    {
     "alias": "Instance 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_instances started_6\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_instances started_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Replica Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Replicas",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Count_of_replicas"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Lambda",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "alias": "Lambda",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_Lambda"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Omega",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Omega",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_Omega"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  {
   "title": "Delta Response",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "alias": "Delta",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       {
        "params": [
         "response_result_data_Node_info_Metrics_Delta"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Read Only",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 104 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Pool_info_Read_only\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Mode",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 104 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Node_info_Mode\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Suspicious Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 104 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Pool_info_Suspicious_nodes\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "HDD Used",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 104 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Hardware_HDD_used_by_node\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  { "title": "Software Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Sovrin Version",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 113 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"status_software_sovrin\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Indy Version",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 113 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"status_software_indy-node\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 113 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Software_OS_version\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "POC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "collapsed": true,
   "panels": [
    {
     "title": "POC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"status_ok\" and\r\n    r.network == \"${network}\"\r\n  )\r\n\r\n|> toInt()"
      }
     ]
    }
   ]
  }
 ]
}