{
 "title": "Node Detail",
 "description": "An indepth view at each indivudial node",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": { "query": "label_values(name)" } },
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(node_response_result_data_Pool_info_Reachable_nodes_count{name=\"[[node]]\"}, network)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "timeseries",
   "description": "Node Average Connectivity",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Pool_info_Reachable_nodes_count{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Reachable Nodes"
    },
    {
     "expr": "avg(node_response_result_data_Pool_info_Total_nodes_count{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Total Nodes"
    },
    {
     "expr": "avg(node_response_result_data_Pool_info_Total_nodes_count{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"} - node_response_result_data_Pool_info_f_value{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Write Failure Threshhold"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Status Errors",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_status_errors{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Status Warnings",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_status_warnings{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status Ok",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"status_ok\" and\r\n    r.name == \"${node}\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Read Only",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Pool_info_Read_only\" and\r\n    r.name == \"${node}\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Suspicious Nodes",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Pool_info_Suspicious_nodes\" and\r\n    r.name == \"${node}\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "HDD Used",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Hardware_HDD_used_by_node\" and\r\n    r.name == \"${node}\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Mode",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Node_info_Mode\" and\r\n    r.name == \"${node}\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "IP's",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Client External",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"client-address\" and\r\n    r.name == \"${node}\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Node External",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"node-address\" and\r\n    r.name == \"${node}\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Client Internal",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Client_port{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"}"
    }
   ]
  },
  {
   "title": "Node Internal",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Node_port{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"}"
    },
    {
     "expr": "response_result_data_Node_info_Node_port{job=\"tick\", name=\"[[node]]\"}"
    }
   ]
  },
  {
   "title": "Software Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sovrin Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"status_software_sovrin\" and\r\n    r.name == \"${node}\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Indy Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"status_software_indy-node\" and\r\n    r.name == \"${node}\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Software_OS_version\" and\r\n    r.name == \"${node}\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Keys",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DID",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Node_info_did\" and\r\n    r.name == \"${node}\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "BLSKey",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Node_info_BLS_key\" and\r\n    r.name == \"${node}\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Verkey",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Node_info_verkey\" and\r\n    r.name == \"${node}\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  { "title": "Txn Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Read Txns per Second",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_average_per_second_read_transactions{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Txns per Second"
    }
   ]
  },
  {
   "title": "Write Txns per Second",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_average_per_second_write_transactions{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Txns per Second"
    }
   ]
  },
  {
   "title": "Request Timeouts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ordering Phase Req Timeouts",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Requests_timeouts_Ordering_phase_req_timeouts{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Request timeouts"
    }
   ]
  },
  {
   "title": "Propagates Phase Req Timeouts",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Requests_timeouts_Propagates_phase_req_timeouts{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Request timeouts"
    }
   ]
  },
  {
   "title": "Transaction Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uncommitted Ledger Txns",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Uncommitted_ledger_txns_0_Count{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Ledger 0"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Uncommitted_ledger_txns_1_Count{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Ledger 1"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Uncommitted_ledger_txns_2_Count{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Ledger 2"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Uncommitted_ledger_txns_3_Count{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "ledger 3"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Uncommitted_ledger_txns_1001_Count{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Ledger 1001"
    }
   ]
  },
  {
   "title": "Ledger Txn Count",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_transaction_count_ledger{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Txn Count"
    }
   ]
  },
  {
   "title": "Audit Txn Count",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_transaction_count_audit{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Txn Count"
    }
   ]
  },
  {
   "title": "Config Txn Count",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_transaction_count_config{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Txn Count"
    }
   ]
  },
  {
   "title": "Pool Txn Count",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_transaction_count_pool{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Txn Count"
    }
   ]
  },
  {
   "title": "1001 Txn Count",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_transaction_count_1001{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Txn Count"
    }
   ]
  },
  {
   "title": "Catchup Txn Count",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_0{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Ledger 0"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_1{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Ledger 1"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_2{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Ledger 2"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_3{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Ledger 3"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_1001{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Ledger 1001"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Master Throughput",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_master_throughput{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Master Throughput Ratio",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_master_throughput_ratio{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Master throughput ratio"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_throughput_0{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Throughput 0"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_throughput_1{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Throughput 1"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_throughput_2{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Throughput 2"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_throughput_3{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Throughput 3"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_throughput_4{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Throughput 4"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_throughput_5{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Throughput 5"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_throughput_6{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Throughput 6"
    }
   ]
  },
  {
   "title": "Avg Backup Throughput",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_avg_backup_throughput{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Avg backup throughup"
    }
   ]
  },
  {
   "title": "Max Master Req. Latencies",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_max_master_request_latencies{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Client Avg Request Latencies",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_client_avg_request_latencies_0{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Avg Req. Latencies 0"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_client_avg_request_latencies_1{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Avg Req. Latencies 1"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_client_avg_request_latencies_2{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Avg Req. Latencies 2"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_client_avg_request_latencies_3{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Avg Req. Latencies 3"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_client_avg_request_latencies_4{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Avg Req. Latencies 4"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_client_avg_request_latencies_5{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Avg Req. Latencies 5"
    }
   ]
  },
  {
   "title": "Ordered Request Durations",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_durations_0{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Request 0"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_durations_1{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Request 1"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_durations_2{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Request 2"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_durations_3{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Request 3"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_durations_4{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Request 4"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_durations_5{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Request 5"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_durations_6{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Request 6"
    }
   ]
  },
  {
   "title": "Request Counts",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_total_requests{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_counts_0{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Count 0"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_counts_1{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Count 1"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_counts_2{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Count 2"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_counts_3{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Count 3"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_counts_4{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Count 4"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_counts_5{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Count 5"
    },
    {
     "expr": "avg(node_response_node_response_result_data_Node_info_Metrics_ordered_request_counts_6{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Count 6"
    }
   ]
  },
  {
   "title": "Instances Started",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_instances_started_0{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Instance 0"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_instances_started_1{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Instance 1"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_instances_started_2{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Instance 2"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_instances_started_3{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Instance 3"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_instances_started_4{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Instance 4"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_instances_started_5{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Instance 5"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_instances_started_6{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Instance 6"
    }
   ]
  },
  {
   "title": "Replica Count",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Count_of_replicas{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Replicas"
    }
   ]
  },
  {
   "title": "Lambda",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_Lambda{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Lambda"
    }
   ]
  },
  {
   "title": "Omega",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_Omega{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Omega"
    }
   ]
  },
  {
   "title": "Delta Response",
   "type": "timeseries",
   "description": "Node Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_Delta{job=\"tick\", name=\"[[node]]\", network=\"[[network]]\"})",
     "legendFormat": "Delta"
    }
   ]
  },
  { "title": "Quorums", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Quorums",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 116 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Pool_info_Quorums\" and\r\n    r.name == \"${node}\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  }
 ]
}