{
 "title": "Prometheus Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": { "query": "label_values(name)" } }
  ]
 },
 "panels": [
  { "title": "External Address", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client Address",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"client-address\" and\r\n    r.name == \"${node}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Node Address",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"node-address\" and\r\n    r.name == \"${node}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  { "title": "Internal Address", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Client Address",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Client_port{job=\"tick\", name=\"[[node]]\"}"
    }
   ]
  },
  {
   "title": "Node Address",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Node_port{job=\"tick\", name=\"[[node]]\"}"
    },
    {
     "expr": "response_result_data_Node_info_Node_port{job=\"tick\", name=\"[[node]]\"}"
    }
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Node Connectivity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_response_result_data_Pool_info_Total_nodes_count{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Total Nodes"
    },
    {
     "expr": "node_response_result_data_Pool_info_Reachable_nodes_count{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Reachable Nodes"
    },
    {
     "expr": "node_response_result_data_Pool_info_Unreachable_nodes_count{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Unreachable Nodes"
    },
    {
     "expr": "node_response_result_data_Pool_info_Total_nodes_count{job=\"tick\", name=\"[[node]]\"} - node_response_result_data_Pool_info_f_value{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Write Failure Threshhold"
    }
   ]
  },
  {
   "title": "Read Txns per Second (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_average_per_second_read_transactions{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Txns per Second"
    }
   ]
  },
  {
   "title": "Write Txns per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_average_per_second_write_transactions{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Txns per Second"
    }
   ]
  },
  {
   "title": "Status Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_status_errors{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Status Warnings",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_status_warnings{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Warnings"
    }
   ]
  },
  { "title": "Software Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Sovrin Version",
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"status_software_sovrin\" and\r\n    r.name == \"${node}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Indy Version",
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"status_software_indy-node\" and\r\n    r.name == \"${node}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  { "title": "Request Timeouts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Ordering Phase Req Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Requests_timeouts_Ordering_phase_req_timeouts{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Request timeouts"
    }
   ]
  },
  {
   "title": "Propagates Phase Req Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Requests_timeouts_Propagates_phase_req_timeouts{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Request timeouts"
    }
   ]
  },
  { "title": "Transaction Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Uncommitted Ledger Txns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Uncommitted_ledger_txns_0_Count{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Ledger 0"
    },
    {
     "expr": "node_response_result_data_Node_info_Uncommitted_ledger_txns_1_Count{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Ledger 1"
    },
    {
     "expr": "node_response_result_data_Node_info_Uncommitted_ledger_txns_2_Count{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Ledger 2"
    },
    {
     "expr": "node_response_result_data_Node_info_Uncommitted_ledger_txns_3_Count{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "ledger 3"
    },
    {
     "expr": "node_response_result_data_Node_info_Uncommitted_ledger_txns_1001_Count{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Ledger 1001"
    }
   ]
  },
  {
   "title": "Catchup Txn Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_0{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Ledger 0"
    },
    {
     "expr": "node_response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_1{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Ledger 1"
    },
    {
     "expr": "node_response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_2{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Ledger 2"
    },
    {
     "expr": "node_response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_3{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Ledger 3"
    },
    {
     "expr": "node_response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_1001{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Ledger 1001"
    }
   ]
  },
  {
   "title": "Replica Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Count_of_replicas{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Replicas"
    }
   ]
  },
  {
   "title": "Master Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_master_throughput{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Omega",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_Omega{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Omega"
    }
   ]
  },
  {
   "title": "Ledger Txn Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_transaction_count_ledger{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Txn Count"
    }
   ]
  },
  {
   "title": "1001 Txn Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_transaction_count_1001{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Txn Count"
    }
   ]
  },
  {
   "title": "Pool Txn Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_transaction_count_pool{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Txn Count"
    }
   ]
  },
  {
   "title": "Config Txn Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_transaction_count_config{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Txn Count"
    }
   ]
  },
  {
   "title": "Audit Txn Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_transaction_count_audit{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Txn Count"
    }
   ]
  },
  { "title": "Plot to see how it displays", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Lambda",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_Lambda{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Lambda"
    }
   ]
  },
  {
   "title": "Instances Started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_instances_started_0{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Instance 0"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_instances_started_1{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Instance 1"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_instances_started_2{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Instance 2"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_instances_started_3{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Instance 3"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_instances_started_4{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Instance 4"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_instances_started_5{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Instance 5"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_instances_started_6{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Instance 6"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_throughput_0{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Throughput 0"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_throughput_1{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Throughput 1"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_throughput_2{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Throughput 2"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_throughput_3{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Throughput 3"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_throughput_4{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Throughput 4"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_throughput_5{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Throughput 5"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_throughput_6{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Throughput 6"
    }
   ]
  },
  {
   "title": "Quorums",
   "type": "table",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 78 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Pool_info_Quorums\" and\r\n    r.name == \"${node}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Client Avg Request Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_client_avg_request_latencies_0{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Avg Req. Latencies 0"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_client_avg_request_latencies_1{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Avg Req. Latencies 1"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_client_avg_request_latencies_2{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Avg Req. Latencies 2"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_client_avg_request_latencies_3{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Avg Req. Latencies 3"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_client_avg_request_latencies_4{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Avg Req. Latencies 4"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_client_avg_request_latencies_5{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Avg Req. Latencies 5"
    }
   ]
  },
  {
   "title": "Request Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 81 },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_total_requests{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_ordered_request_counts_0{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Count 0"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_ordered_request_counts_1{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Count 1"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_ordered_request_counts_2{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Count 2"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_ordered_request_counts_3{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Count 3"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_ordered_request_counts_4{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Count 4"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_ordered_request_counts_5{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Count 5"
    },
    {
     "expr": "node_response_node_response_result_data_Node_info_Metrics_ordered_request_counts_6{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Count 6"
    }
   ]
  },
  {
   "title": "Max Master Req. Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 81 },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_max_master_request_latencies{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Delta Response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_Delta{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Delta"
    }
   ]
  },
  {
   "title": "Ordered Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 89 },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_ordered_request_durations_0{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Request 0"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_ordered_request_durations_1{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Request 1"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_ordered_request_durations_2{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Request 2"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_ordered_request_durations_3{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Request 3"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_ordered_request_durations_4{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Request 4"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_ordered_request_durations_5{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Request 5"
    },
    {
     "expr": "node_response_result_data_Node_info_Metrics_ordered_request_durations_6{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Request 6"
    }
   ]
  },
  {
   "title": "Avg Backup Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 89 },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_avg_backup_throughput{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Avg backup throughup"
    }
   ]
  },
  {
   "title": "Master Throughput Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "node_response_result_data_Node_info_Metrics_master_throughput_ratio{job=\"tick\", name=\"[[node]]\"}",
     "legendFormat": "Master throughput ratio"
    }
   ]
  },
  {
   "title": "Read Only",
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 97 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Pool_info_Read_only\" and\r\n    r.name == \"${node}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Suspicious Nodes",
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 97 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Pool_info_Suspicious_nodes\" and\r\n    r.name == \"${node}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Status Ok",
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 97 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"status_ok\" and\r\n    r.name == \"${node}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Mode",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 97 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Node_info_Mode\" and\r\n    r.name == \"${node}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "HDD Used",
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 97 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Hardware_HDD_used_by_node\" and\r\n    r.name == \"${node}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "BLSKey",
   "type": "table",
   "gridPos": { "h": 2, "w": 6, "x": 8, "y": 99 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Node_info_BLS_key\" and\r\n    r.name == \"${node}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Verkey",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 100 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Node_info_verkey\" and\r\n    r.name == \"${node}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "DID",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 101 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Node_info_did\" and\r\n    r.name == \"${node}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "table",
   "gridPos": { "h": 2, "w": 7, "x": 15, "y": 103 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Software_OS_version\" and\r\n    r.name == \"${node}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  }
 ]
}