{
 "title": "Public Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "SHOW TAG VALUES FROM \"node\" WITH KEY = \"network\" "
    }
   }
  ]
 },
 "panels": [
  {
   "type": "timeseries",
   "description": "Network Average Node Connectivity",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Reachable Nodes",
     "query": "SELECT mean(\"response_result_data_Pool_info_Total_nodes_count\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Total Nodes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"response_result_data_Pool_info_Total_nodes_count\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Write Failure Threshhold",
     "query": "SELECT max(\"response_result_data_Pool_info_Total_nodes_count\") - max(\"response_result_data_Pool_info_f_value\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Status Errors",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Errors",
     "query": "SELECT max(\"status_errors\") FROM \"autogen\".\"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($interval)"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Status Warnings",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Warnings",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"status_warnings\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Txn Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Read Txns per Second",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Txns per Second",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_average-per-second_read-transactions\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Write Txns per Second",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Txns per Second",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_average-per-second_write-transactions\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  { "title": "Transaction Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Ledger Txn Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Txn Count",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_transaction-count_ledger\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Audit Txn Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Txn Count",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_transaction-count_audit\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Config Txn Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Txn Count",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_transaction-count_config\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Pool Txn Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Txn Count",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_transaction-count_pool\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "1001 Txn Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Txn Count",
     "query": "SELECT mean(\"response_result_data_Node_info_Metrics_transaction-count_1001\") FROM \"node\" WHERE (\"network\"::tag =~ /^$network$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  }
 ]
}