{
 "title": "Top Layer Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": { "query": "label_values(network)" } }
  ]
 },
 "panels": [
  {
   "type": "gauge",
   "description": "Warnings and Errors Status",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "Warning = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) => \r\n     r._measurement == \"node\" and \r\n     r._field == \"status_warnings\" and \r\n     r.network == \"${network}\"\r\n     )\r\n\r\nError = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"status_errors\" and \r\n    r.network == \"${network}\" \r\n  )\r\n\r\n  join(\r\n    tables: {status_warnings:Warning, status_errors:Error},\r\n    on: [\"_time\", \"_stop\", \"_start\", \"host\", \"name\", \"url\", \"network\", \"_measurement\"],\r\n)\r\n\r\n  |> map(fn: (r) => ({r with\r\n    Final: if r._value_status_errors >= 1 then\r\n      0\r\n    else if r._value_status_warnings >= 1 then\r\n      1\r\n    else 3\r\n    })\r\n    )"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Network Average Node Connectivity",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(avg(node_response_result_data_Pool_info_Reachable_nodes_count{job=\"tick\", network=\"[[network]]\"}))",
     "legendFormat": "Reachable Nodes"
    },
    {
     "expr": "min(node_response_result_data_Pool_info_Total_nodes_count{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Total Nodes"
    },
    {
     "expr": "max(node_response_result_data_Pool_info_Total_nodes_count{job=\"tick\", network=\"[[network]]\"} - node_response_result_data_Pool_info_f_value{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Write Failure Threshhold"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Status Errors",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(node_status_errors{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Status Warnings",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(node_status_warnings{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Warnings"
    }
   ]
  },
  { "title": "Txn Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Read Txns per Second",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_average_per_second_read_transactions{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Txns per Second"
    }
   ]
  },
  {
   "title": "Write Txns per Second",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_average_per_second_write_transactions{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Txns per Second"
    }
   ]
  },
  { "title": "Request Timeouts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Ordering Phase Req Timeouts",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Requests_timeouts_Ordering_phase_req_timeouts{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Request timeouts"
    }
   ]
  },
  {
   "title": "Propagates Phase Req Timeouts",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Requests_timeouts_Propagates_phase_req_timeouts{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Request timeouts"
    }
   ]
  },
  { "title": "Transaction Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Uncommitted Ledger Txns",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Uncommitted_ledger_txns_0_Count{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Ledger 0"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Uncommitted_ledger_txns_1_Count{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Ledger 1"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Uncommitted_ledger_txns_2_Count{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Ledger 2"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Uncommitted_ledger_txns_3_Count{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "ledger 3"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Uncommitted_ledger_txns_1001_Count{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Ledger 1001"
    }
   ]
  },
  {
   "title": "Ledger Txn Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_transaction_count_ledger{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Txn Count"
    }
   ]
  },
  {
   "title": "Audit Txn Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_transaction_count_audit{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Txn Count"
    }
   ]
  },
  {
   "title": "Config Txn Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_transaction_count_config{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Txn Count"
    }
   ]
  },
  {
   "title": "Pool Txn Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_transaction_count_pool{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Txn Count"
    }
   ]
  },
  {
   "title": "1001 Txn Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_transaction_count_1001{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Txn Count"
    }
   ]
  },
  {
   "title": "Catchup Txn Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_0{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Ledger 0"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_1{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Ledger 1"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_2{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Ledger 2"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_3{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Ledger 3"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Catchup_status_Number_txns_in_catchup_1001{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Ledger 1001"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Master Throughput",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_master_throughput{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Master Throughput Ratio",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_master_throughput_ratio{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Master throughput ratio"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_throughput_0{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Throughput 0"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_throughput_1{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Throughput 1"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_throughput_2{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Throughput 2"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_throughput_3{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Throughput 3"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_throughput_4{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Throughput 4"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_throughput_5{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Throughput 5"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_throughput_6{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Throughput 6"
    }
   ]
  },
  {
   "title": "Avg Backup Throughput",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_avg_backup_throughput{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Avg backup throughup"
    }
   ]
  },
  {
   "title": "Max Master Req. Latencies",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "max(node_response_result_data_Node_info_Metrics_max_master_request_latencies{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Client Avg Request Latencies",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_client_avg_request_latencies_0{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Avg Req. Latencies 0"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_client_avg_request_latencies_1{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Avg Req. Latencies 1"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_client_avg_request_latencies_2{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Avg Req. Latencies 2"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_client_avg_request_latencies_3{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Avg Req. Latencies 3"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_client_avg_request_latencies_4{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Avg Req. Latencies 4"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_client_avg_request_latencies_5{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Avg Req. Latencies 5"
    }
   ]
  },
  {
   "title": "Ordered Request Durations",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_durations_0{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Request 0"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_durations_1{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Request 1"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_durations_2{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Request 2"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_durations_3{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Request 3"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_durations_4{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Request 4"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_durations_5{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Request 5"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_durations_6{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Request 6"
    }
   ]
  },
  {
   "title": "Request Counts",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_total_requests{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_counts_0{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Count 0"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_counts_1{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Count 1"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_counts_2{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Count 2"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_counts_3{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Count 3"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_counts_4{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Count 4"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_ordered_request_counts_5{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Count 5"
    },
    {
     "expr": "avg(node_response_node_response_result_data_Node_info_Metrics_ordered_request_counts_6{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Count 6"
    }
   ]
  },
  {
   "title": "Instances Started",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_instances_started_0{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Instance 0"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_instances_started_1{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Instance 1"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_instances_started_2{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Instance 2"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_instances_started_3{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Instance 3"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_instances_started_4{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Instance 4"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_instances_started_5{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Instance 5"
    },
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_instances_started_6{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Instance 6"
    }
   ]
  },
  {
   "title": "Replica Count",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Count_of_replicas{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Replicas"
    }
   ]
  },
  {
   "title": "Lambda",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_Lambda{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Lambda"
    }
   ]
  },
  {
   "title": "Omega",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_Omega{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Omega"
    }
   ]
  },
  {
   "title": "Delta Response",
   "type": "timeseries",
   "description": "Network Average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "avg(node_response_result_data_Node_info_Metrics_Delta{job=\"tick\", network=\"[[network]]\"})",
     "legendFormat": "Delta"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Read Only",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 104 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Pool_info_Read_only\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Mode",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 104 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Node_info_Mode\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Suspicious Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 104 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Pool_info_Suspicious_nodes\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "HDD Used",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 104 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Hardware_HDD_used_by_node\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  { "title": "Software Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Sovrin Version",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 113 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"status_software_sovrin\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "Indy Version",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 113 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"status_software_indy-node\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 113 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"response_result_data_Software_OS_version\" and\r\n    r.network == \"${network}\"\r\n  )\r\n  |> yield()\r\n  "
    }
   ]
  },
  {
   "title": "POC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "collapsed": true,
   "panels": [
    {
     "title": "POC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"node\" and \r\n    r._field == \"status_ok\" and\r\n    r.network == \"${network}\"\r\n  )\r\n\r\n|> toInt()"
      }
     ]
    }
   ]
  }
 ]
}