{
 "title": "Indicio Test Network",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "\"cynjanode\",\"OpsNode\",\"Uphold\",\"IdRamp\",\"GlobaliD\""
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "host",
    "label": "Host:",
    "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 13 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  }
 ]
}