{
 "title": "Sovrin MainNet",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "\"BIGAWSUSEAST1-001\",\"DustStorm\",\"OASFCU\",\"ServerVS\",\"Stuard\",\"TNO\",\"VeridiumIDC\",\"atbsovrin\",\"danube\",\"esatus_AG\",\"ev1\",\"findentity\",\"iRespond\",\"icenode\",\"pcValidator01\",\"prosovitor\",\"royal_sovrin\",\"sovrin.sicpa.com\",\"sparknz\",\"zaValidator\""
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "host",
    "label": "Host:",
    "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 13 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 16 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 19 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 22 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 25 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 28 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 31 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 37 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 40 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 43 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 46 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 49 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 52 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 52 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 55 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 55 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "$node Uptime",
   "type": "singlestat",
   "description": "Indy Validator Node uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 58 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_uptime{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Unreachable Nodes",
   "type": "singlestat",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 58 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Primary Node",
   "type": "stat",
   "description": "Indy Validator Primary Node",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "indy_primary_node{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Indy-Node Version",
   "type": "stat",
   "description": "Indy Validator indy-node version",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "indy_node_version{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$node Consensus Status",
   "type": "stat",
   "description": "Indy Validator Node Ledger Consensus status",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  },
  {
   "title": "$node Current Timestamp",
   "type": "stat",
   "description": "Indy Validator Node current date/time",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indy_node_current_timestamp{instance=\"localhost:9103\",job=\"node-external\",node_name=${node:raw}}"
    }
   ]
  }
 ]
}