# This workflow will install Python dependencies and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      working-directory: fetch-validator-status
      run: pipenv install
    - name: Test with unittest
      working-directory: fetch-validator-status
      run: pipenv run python -m unittest test_prometheus_exporter
